### ISSUE TITLE
Pivot todo

### ISSUE THREAD

**Issue by dillingham** [headlesslaravel/formations#2]
- [ ] add pivot method policy checks
- [ ] add pivot table column support 
- [ ] refactor public methods like formationWIthPivot()
